### ISSUE TITLE
POST /embeddings/ HTTP/1.1" 504 Gateway Timeout

### ISSUE THREAD

**Issue by kkkjho** [puppetm4st3r/baai_m3_simple_server#1]
Call embedding api, raise 504 gateway timeout occure.

$ python m3_server.py
Fetching 30 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 50881.16it/s]
INFO:     Started server process [71466]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
starting processing_loop
INFO:     127.0.0.1:57650 - "POST /embeddings/ HTTP/1.1" 504 Gateway Timeout

$ curl -X POST http://0.0.0.0:3000/embeddings/ -H "accept: application/json" -H "Content-Type: application/json" \ 
-d '{
   "sentences": [
     "This is the first example sentence.",
     "Here goes the second example."
   ]
}'
{"detail":"Request processing time excedeed limit","processing_time":30.00098991394043}

**Comment by puppetm4st3r** [comment]
can you share more context? 

1) running environment
2) running on gpu?
3) do you change any setting or its the fresh cloned code?
4) have you try the test.sh script?

thanks

**Comment by kkkjho** [comment]
1. running environment
   -> Ubuntu 20.04
2. running on gpu?
   ->  I've tried both CPU only and NVIDIA T4, but it doesn't work. (same error 504 timeout)
3. do you change any setting or its the fresh cloned code?
   -> No
4. have you try the test.sh script?
   -> Yes, same error (I`ve change port number 8000 to 3000 only)
$ sh -v test.sh 2
{"detail":"Request processing time excedeed limit","processing_time":30.000566720962524}{"detail":"Request processing time excedeed limit","processing_time":30.004218339920044}{"deta

Do you have any advice? help me..
Thanks!

**Comment by puppetm4st3r** [comment]
are you running on a local machine or in the cloud?

and how much time have to to wait from the request until the timeout message? its instantly ?

**Comment by kkkjho** [comment]
running on cloud and timeout occured after  30sec.

**Comment by puppetm4st3r** [comment]
can you try increasing the timeout settings?

request_time_out = 30  # Timeout threshold
gpu_time_out = 5 # gpu processing timeout threshold

to 300 each, I was never try this model on cpu and when I used on gpu was on a 4090rtx, this model is a little resource demanding model, may be you are running out of time to complete the inference in the hardware you are deploying, also dont know is the model support T gpu families, can you try on a newer gpu like an A series ?

regards

**Comment by kkkjho** [comment]
I upgrade python 3.9.5 to 3.11.9 and it works.
Thanks!

**Comment by puppetm4st3r** [comment]
thanks to you, will put that on the readme
